### ISSUE TITLE
Generate output as a data.frame

### ISSUE THREAD

**Issue by mtkent1** [benjaminrich/table1#17] opened 2019-06-30 13:07 UTC
Is it or would it be possible to allow the output be a data.frame instead of an html object? Sometimes it is nice to manipulate the basic table further in an RMarkdown doc using tools like kableExtra.

**Comment by benjaminrich** [comment] 2019-07-01 15:55
This was never a design goal for this package. The problem is that a data.frame lacks **structure**: you can't distinguish between data and labels, can (easily) do cell alignment or indenting, can't have merged cells, and so on. In my mind, a table is much more than just a grid of cells.

But something like this may come in a future version (a few others have asked for it). But there is no development roadmap and I can't really say when it might be done - I don't really have the ability to predict when I'll have the resources. In the meantime, you may want to check out other packages such as furniture or tableone and see they suit your needs better.

But I'm curious as to to types of manipulations you have in mind, because quite a bit of flexibility can be achieved using the current feature set. Would you care to give an example?

**Comment by mtkent1** [comment] 2019-07-05 15:54
Definitely understand that. I have been thinking more about using `kableExtra` or the new `gt` (https://github.com/rstudio/gt) for the formatting of the table once it was in a data.frame. However, I do like how easy the current package produces great HTML output that can be easily incorporated everywhere.

This question really come from having to stratify a table by one variable and then creating multiple tables for different cohorts of the data. For example, cohort A, B, and C, would be stratified by variable A, which has three levels. I could create a table with 9 columns, but it would be nice to "stack" these tables and then label were the next cohort starts, similar to `pack_rows` in the `kableExtra` package.

**Comment by benjaminrich** [comment] 2019-07-05 16:02
OK, I think I see where you are coming from. You have 3 variables with 3 levels each that you want to stratify by, and you want to stratify by columns AND rows. I'll give it some thought. Are you able to post a picture of what the results should look like?

**Comment by mtkent1** [comment] 2019-07-05 17:08
Yep, that's right. I think of it in a similar way to this: https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#group_rows_via_labeling

Where the groups would be considered the row filtering.

**Comment by smouksassi** [comment] 2019-07-19 11:48
isnt it the goal of fable to support these kind of tables ?

**Comment by benjaminrich** [comment] 2019-07-19 12:56
Yes, sort of, maybe (@smouksassi is referring to [another package](https://github.com/benjaminrich/fable) I am developing, slowly). But `fable` works differently. Even though it works well, it has not been released yet, and some documentation is lacking.

@mtkent1, the problem I see with `kableExtra` is that in `table1` rows are already grouped by variables. I don't think that `kableExtra` allows two levels of grouping, which is what you would need. Correct me if I'm wrong.

**Comment by mtkent1** [comment] 2019-08-01 13:55
Actually, I think the `rvest` package might solve this problem for me (although you do lose some of the structure of the table but it works "well" enough).

If `tbl_1` is a `table1` table then:

```
library(rvest)
as.data.frame(read_html(tbl_1) %>% html_table(fill=TRUE))
```

will return a `data.frame` with the table data.

**Comment by ck2136** [comment] 2020-04-06 19:29
> 
> 
> Actually, I think the `rvest` package might solve this problem for me (although you do lose some of the structure of the table but it works "well" enough).
> 
> If `tbl_1` is a `table1` table then:
> 
> ```
> library(rvest)
> as.data.frame(read_html(tbl_1) %>% html_table(fill=TRUE))
> ```
> 
> will return a `data.frame` with the table data.

I've tried the code by @mtkent1  above and what I found that preserved the column headers better was 
```
library(rvest)
as_tibble(read_html(tbl_1) %>% html_table(fill=TRUE))
```

**Comment by benjaminrich** [comment] 2021-04-16 14:49
This feature is finally coming, in version 1.4.

**Comment by benjaminrich** [comment] 2021-04-28 13:52
Version 1.4 was just released. `table1` objects can now be converted to `data.frame` with `as.data.frame()`.

**Closed by benjaminrich** 2021-04-28 13:52 UTC
Labels: feature request
