### ISSUE TITLE
Strange statistics for some values

### ISSUE THREAD

**Issue by wiedenhoeft** [benjaminrich/table1#24] opened 2019-12-17 11:51 UTC
I'm getting some wrong means, minima and maxima for some values in version 1.1:
```
library(table1)
library(tidyverse)
d <- tibble(Year=c(rep(2017, 100), rep(2018, 100)))
table1(~., data=d)
```
I get
<table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(n=200)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'><span class='varlabel'>Year</span></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>2020 (0.501)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>2020 [2020, 2020]</td>
</tr>
</tbody>
</table>

which is clearly wrong. However, changing the values to 207 and 208, I get

<table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(n=200)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'><span class='varlabel'>Year</span></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>208 (0.501)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>208 [207, 208]</td>
</tr>
</tbody>
</table>

which is only slightly off (mean and median are wrong, but not min and max). For 27 and 28, I get

<table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(n=200)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'><span class='varlabel'>Year</span></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>27.5 (0.501)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>27.5 [27.0, 28.0]</td>
</tr>
</tbody>
</table>

which appears to be correct.

**Comment by benjaminrich** [comment] 2019-12-17 13:11
This is actually just a rounding issue.  To get the result you expect do:

```r
table1(~., data=d, digits=5)
```

  | Overall(N=200)
-- | --
Year |  
Mean (SD) | 2017.5 (0.50125)
Median [Min, Max] | 2017.5 [2017.0, 2018.0]

Proper rounding behaviour is a bit subjective. By default, `table1` will round most statistics to 3 *significant digits*, and that includes integers, so, for example, 2017.5 gets rounded to 2020. This may seem odd in your example, but in many cases it makes sense (again, it is somewhat subjective, but rounding at some level is necessary). Hence, what you are observing is actually expected behaviour.

There are a couple of other options related to rounding that are worth mentioning. You can turn rounding off for the *integer* part of numbers (i.e., only the decimal part will be rounded) with:

```r
table1(~., data=d, round.integers=F)
```

  | Overall(N=200)
-- | --
Year |  
Mean (SD) | 2018 (0.501)
Median [Min, Max] | 2018 [2017, 2018]

Now, 2017.5 gets rounded to the nearest integer, while the SD continues to be rounded to 3 significant digits.

You can turn rounding off just for the median, min and max with:

```r
table1(~., data=d, round.median.min.max=F)
```

  | Overall(N=200)
-- | --
Year |  
Mean (SD) | 2020 (0.501)
Median [Min, Max] | 2017.5 [2017, 2018]

For finer control of rounding you would have to write your own rendering function.

**Comment by wiedenhoeft** [comment] 2019-12-18 13:07
While I understand why one might report only a certain number of significant digits, this is hardly expected behavior from a user perspective (I'd assume that the standard functions such as mean() and sd() are being used), as min/max neither gives the correct range of values to spot outliers, nor do mean and median lie within the actual range of the data, which is highly misleading. Might I suggest to adapt the default behavior to operate on the variable-wise input precision, i.e. on the lowest non-zero digit for any given variable? I could live with mean(2017, 2018)= 2018, but certainly not 2020.

**Comment by benjaminrich** [comment] 2019-12-18 13:31
As I said, there are plenty of options to control how the rounding operates. The default may not give the expected result in your case, but your case is hardly the typical use case, it's a highly contrived example. In the field I work in, when large numbers are reported I can't really trust more than the first few digits. That may not apply to everyone, which is why I have made the package flexible enough to accommodate different needs. While I appreciate your suggestions about trying to "guess" the input precision from the data, I believe it will be error prone and lead to confusion for the user, whereas the current default behaviour is simple and consistent (you just need to be aware of it).

**Comment by wiedenhoeft** [comment] 2019-12-18 13:44
It is certainly your prerogative to make the design decisions, but I'm afraid I have to disagree. Though Year is indeed an atypical example (this is how I spotted that behavior, by accidentally leaving the year column in my data frame), having large integers is not atypical. If I measure to a certain precision (e.g. counting participants in a large cohort, or cells in a sample), I expect this to be respected in downstream calculations. The very least I expect is that the relative positions of summary statistics (min, median, mean, max) are preserved. I appreciate having the options to tweak this behavior, I'm just saying they should be set to TRUE by default ;-)

**Comment by benjaminrich** [comment] 2019-12-18 15:07
I never said that large integers are unusual, but it's up to the user to specify the precision to which they are measured (using `digits`), in my opinion. I will not try to guess that from the data using some heuristic.

In the past, I had considered `round.integers=F` the default, but this some disadvantages in my opinion. Suppose I have some large integers and I know that they are accurate to 4 significant digits:

```r
set.seed(123)
d <- data.frame(x=signif(rnorm(1000, 1e8, 1e7), 4))
table1(~., data=d, round.integers=F)
```

  | Overall(N=1000)
-- | --
x |  
Mean (SD) | 100161570 (9917806)
Median [Min, Max] | 100100000 [71900000, 132400000]

In this case, the median/min/max are OK, but the mean and SD are overly precise. Like I said, the default is simple and consistent, but obviously does not cover every case. And different rules may be applicable to different variables in the same table, which can be accomplished using a custom render function.

**Comment by benjaminrich** [comment] 2019-12-18 15:32
Then, you could think that `round.median.min.max=F` should be the default because at least there you are respecting the precision of the data. But this also has issues. In your example, I consider


  | Overall(N=200)
-- | --
Year |  
Mean (SD) | 2020 (0.501)
Median [Min, Max] | 2020 [2020, 2020]

to be correct *to 3 significant digits*, whereas


  | Overall(N=200)
-- | --
Year |  
Mean (SD) | 2020 (0.501)
Median [Min, Max] | 2017.5 [2017, 2018]

is clearly wrong (how could the mean be less than minimum?). Thus, again, the current default is simple and consistent (though not perfect).

**Comment by benjaminrich** [comment] 2020-01-02 17:01
Closing this issue as there are no further comments.

**Closed by benjaminrich** 2020-01-02 17:01 UTC
Labels: expected behavior
